/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab4;

import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author TuanDuc
 */
public class Bai1 extends javax.swing.JFrame {
    void open()
    {
        JFileChooser filec = new JFileChooser();
        int r = filec.showOpenDialog(null);
        if (r == JFileChooser.APPROVE_OPTION)
        {
            File slectFile = filec.getSelectedFile();
            try
            {
                txtaNote.read(new FileReader(slectFile.getAbsoluteFile()), null);
            }
            catch(Exception ex) {ex.printStackTrace();}
        }
    }
    
    void save()
    {
        JFileChooser fileChs = new JFileChooser();
        int r = fileChs.showSaveDialog(null);
        if (r == JFileChooser.APPROVE_OPTION)
        {
            File file = fileChs.getSelectedFile();
            try {
                txtaNote.write(new FileWriter(file.getAbsoluteFile()));
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }
    
    void gioiThieu()
    {
        String str = "Tác giả: TangPhuocSang\n"
                + "Điện thoại: 0706927698\n"
                + "Trường: FPT Polytechnic\n"
                
                + "Môn: Java 3 \n"
                + "Bài: Bài 1 Lab 4";
        JOptionPane.showMessageDialog(this, str);
    }
    
    void thoat()
    {
        int r = JOptionPane.showConfirmDialog(this, "Bạn thật sự muốn thoát?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (r == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }
    
    public Bai1() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOpen = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaNote = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuNew = new javax.swing.JMenuItem();
        mnuOpen = new javax.swing.JMenuItem();
        mnuSave = new javax.swing.JMenuItem();
        mnuMau = new javax.swing.JMenu();
        mnuDo = new javax.swing.JMenuItem();
        mnuXanhLa = new javax.swing.JMenuItem();
        mnuXanhDuong = new javax.swing.JMenuItem();
        mnuTextBox = new javax.swing.JMenuItem();
        mnuHeThong = new javax.swing.JMenu();
        mnuGioiThieu = new javax.swing.JMenuItem();
        mnuThoat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Notepad");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOpen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab4/open.png"))); // NOI18N
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab4/exit.png"))); // NOI18N
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab4/people.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOpen)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnThoat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnOpen)
                .addComponent(btnThoat)
                .addComponent(btnSave))
        );

        txtaNote.setColumns(20);
        txtaNote.setRows(5);
        jScrollPane1.setViewportView(txtaNote);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ps14673-TangPhuocSang - Java 3");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mnuFile.setText("File");

        mnuNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab4/plus.png"))); // NOI18N
        mnuNew.setText("New      Ctrl+N");
        mnuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewActionPerformed(evt);
            }
        });
        mnuFile.add(mnuNew);

        mnuOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab4/open.png"))); // NOI18N
        mnuOpen.setText("Open    Ctrl+O");
        mnuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpenActionPerformed(evt);
            }
        });
        mnuFile.add(mnuOpen);

        mnuSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab4/save.png"))); // NOI18N
        mnuSave.setText("Save     Ctrl+S");
        mnuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSaveActionPerformed(evt);
            }
        });
        mnuFile.add(mnuSave);

        jMenuBar1.add(mnuFile);

        mnuMau.setText("Màu");

        mnuDo.setText("Red");
        mnuDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDoActionPerformed(evt);
            }
        });
        mnuMau.add(mnuDo);

        mnuXanhLa.setText("Green");
        mnuXanhLa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuXanhLaMouseClicked(evt);
            }
        });
        mnuXanhLa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuXanhLaActionPerformed(evt);
            }
        });
        mnuMau.add(mnuXanhLa);

        mnuXanhDuong.setText("Blue");
        mnuXanhDuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuXanhDuongActionPerformed(evt);
            }
        });
        mnuMau.add(mnuXanhDuong);

        mnuTextBox.setText("text box");
        mnuTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTextBoxActionPerformed(evt);
            }
        });
        mnuMau.add(mnuTextBox);

        jMenuBar1.add(mnuMau);

        mnuHeThong.setText("Hệ thống");
        mnuHeThong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuHeThongMouseClicked(evt);
            }
        });

        mnuGioiThieu.setText("About us");
        mnuGioiThieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuGioiThieuMouseClicked(evt);
            }
        });
        mnuGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGioiThieuActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuGioiThieu);

        mnuThoat.setText("Exit");
        mnuThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuThoatMouseClicked(evt);
            }
        });
        mnuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThoatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuThoat);

        jMenuBar1.add(mnuHeThong);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 272, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewActionPerformed
        txtaNote.setText(null);
        txtaNote.requestFocus();
    }//GEN-LAST:event_mnuNewActionPerformed

    private void mnuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSaveActionPerformed
        save();
    }//GEN-LAST:event_mnuSaveActionPerformed

    private void mnuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpenActionPerformed
        open();
    }//GEN-LAST:event_mnuOpenActionPerformed

    private void mnuDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDoActionPerformed
        txtaNote.setForeground(Color.red);
    }//GEN-LAST:event_mnuDoActionPerformed

    private void mnuXanhLaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuXanhLaMouseClicked
        txtaNote.setForeground(Color.green);
    }//GEN-LAST:event_mnuXanhLaMouseClicked

    private void mnuXanhDuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuXanhDuongActionPerformed
        txtaNote.setForeground(Color.blue);
    }//GEN-LAST:event_mnuXanhDuongActionPerformed

    private void mnuGioiThieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuGioiThieuMouseClicked
        gioiThieu();
    }//GEN-LAST:event_mnuGioiThieuMouseClicked

    private void mnuThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuThoatMouseClicked
        thoat();
    }//GEN-LAST:event_mnuThoatMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        thoat();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        open();
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        save();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void mnuTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTextBoxActionPerformed
        Color c = JColorChooser.showDialog(this, "Chọn màu chữ", Color.white);
        txtaNote.setForeground(c);
    }//GEN-LAST:event_mnuTextBoxActionPerformed

    private void mnuHeThongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuHeThongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuHeThongMouseClicked

    private void mnuGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGioiThieuActionPerformed
        gioiThieu();
    }//GEN-LAST:event_mnuGioiThieuActionPerformed

    private void mnuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThoatActionPerformed
        thoat();
    }//GEN-LAST:event_mnuThoatActionPerformed

    private void mnuXanhLaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuXanhLaActionPerformed
        txtaNote.setForeground(Color.green);
    }//GEN-LAST:event_mnuXanhLaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuDo;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuGioiThieu;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuMau;
    private javax.swing.JMenuItem mnuNew;
    private javax.swing.JMenuItem mnuOpen;
    private javax.swing.JMenuItem mnuSave;
    private javax.swing.JMenuItem mnuTextBox;
    private javax.swing.JMenuItem mnuThoat;
    private javax.swing.JMenuItem mnuXanhDuong;
    private javax.swing.JMenuItem mnuXanhLa;
    private javax.swing.JTextArea txtaNote;
    // End of variables declaration//GEN-END:variables
}
