/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Lab1;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author TuanDuc
 */
public class Bai2 extends javax.swing.JFrame {
    boolean ktSoA()
    {
        if (txtA.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số");
            txtA.setText(null);
            txtA.setBackground(Color.yellow);
            txtA.requestFocus();
            return false;
        }
        
        try 
        {
            int soa = Integer.parseInt(txtA.getText());
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số");
            txtA.setText(null);
            txtA.setBackground(Color.yellow);
            txtA.requestFocus();
            return false;
        }
        return true;
    }
    
    boolean ktSoB()
    {
        if (txtB.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số");
            txtB.setText(null);
            txtB.setBackground(Color.yellow);
            txtB.requestFocus();
            return false;
        }
        
        try 
        {
            int sob = Integer.parseInt(txtB.getText());
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số");
            txtB.setText(null);
            txtB.setBackground(Color.yellow);
            txtB.requestFocus();
            return false;
        }
        return true;
    }
    
    void cong()
    {
        if (ktSoA() && ktSoB())
        {
            int soa = Integer.parseInt(txtA.getText());
            int sob = Integer.parseInt(txtB.getText());
            int tong = soa + sob;
            txtKQ.setText(String.valueOf(tong));
        }
    }
    
    void tru()
    {
        if (ktSoA() && ktSoB())
        {
            int soa = Integer.parseInt(txtA.getText());
            int sob = Integer.parseInt(txtB.getText());
            int tru = soa - sob;
            txtKQ.setText(String.valueOf(tru));
        }
    }
    
    void nhan()
    {
        if (ktSoA() && ktSoB())
        {
            int soa = Integer.parseInt(txtA.getText());
            int sob = Integer.parseInt(txtB.getText());
            int nhan = soa * sob;
            txtKQ.setText(String.valueOf(nhan));
        }
    }
    
    void chia()
    {
        if (ktSoA() && ktSoB())
        {
            int soa = Integer.parseInt(txtA.getText());
            int sob = Integer.parseInt(txtB.getText());
            int chia = soa / sob;
            txtKQ.setText(String.valueOf(chia));
        }
    }
    
    
    public Bai2() {
        initComponents();
        setLocationRelativeTo(this);
        txtKQ.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKQ = new javax.swing.JTextField();
        btnCong = new javax.swing.JButton();
        btnTru = new javax.swing.JButton();
        btnNhan = new javax.swing.JButton();
        btnChia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Máy tính");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Số A");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Số B");

        txtA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Kết quả");

        txtKQ.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        btnCong.setText("+");
        btnCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCongMouseClicked(evt);
            }
        });

        btnTru.setText("-");
        btnTru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTruMouseClicked(evt);
            }
        });

        btnNhan.setText("*");
        btnNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhanMouseClicked(evt);
            }
        });

        btnChia.setText("/");
        btnChia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKQ)
                            .addComponent(txtB)
                            .addComponent(txtA)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCong, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTru, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtKQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCong)
                    .addComponent(btnTru)
                    .addComponent(btnNhan)
                    .addComponent(btnChia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCongMouseClicked
        cong();
    }//GEN-LAST:event_btnCongMouseClicked

    private void btnTruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTruMouseClicked
        tru();
    }//GEN-LAST:event_btnTruMouseClicked

    private void btnNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanMouseClicked
        nhan();
    }//GEN-LAST:event_btnNhanMouseClicked

    private void btnChiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChiaMouseClicked
        chia();
    }//GEN-LAST:event_btnChiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChia;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnNhan;
    private javax.swing.JButton btnTru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtKQ;
    // End of variables declaration//GEN-END:variables

}
