/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab7;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author TuanDuc
 */
public class Bai2_Server extends javax.swing.JFrame {
    ServerSocket svSocket = null;
    Socket socket = null;
    
    void gui()
    {
        try {
            DataOutputStream opStrem = new DataOutputStream(socket.getOutputStream());
            
            opStrem.writeUTF(txtGui_Server.getText());
            opStrem.flush(); 
        } 
        catch (Exception ex) 
        {
            System.out.println(ex);
            JOptionPane.showMessageDialog(this, "Gửi không được. Lỗi!");
        }
    }
    
    void nhan()
    {
        try {
            DataInputStream ipStrem = new DataInputStream(socket.getInputStream());
            String noiDung = ipStrem.readUTF();       
            txtaNoiDung_Server.setText(noiDung);
        } 
        catch (Exception ex) 
        {
            System.out.println(ex);
            JOptionPane.showMessageDialog(this, "Gửi không được. Lỗi!");
        }
    }
    
    void khoiDong()
    {
        try {
            svSocket = new ServerSocket(Integer.parseInt(txtCong.getText()));
            JOptionPane.showMessageDialog(this, "Server is Connecting....");
            socket = svSocket.accept();
            JOptionPane.showMessageDialog(this, "Server is Connected");
        } catch (Exception ex) 
        {
            System.out.println(ex);
            JOptionPane.showMessageDialog(this, "Vui lòng nhập cổng kết nối.");
            txtCong.requestFocus();
        }
    }
    public Bai2_Server() {
        initComponents();
        setLocationRelativeTo(this);
        txtaNoiDung_Server.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCong = new javax.swing.JTextField();
        btnKhoiDong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaNoiDung_Server = new javax.swing.JTextArea();
        txtGui_Server = new javax.swing.JTextField();
        btnGui = new javax.swing.JButton();
        btnNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Cổng:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Client nói:");

        txtCong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        btnKhoiDong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKhoiDong.setText("Khởi động");
        btnKhoiDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhoiDongMouseClicked(evt);
            }
        });

        txtaNoiDung_Server.setColumns(20);
        txtaNoiDung_Server.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtaNoiDung_Server.setRows(5);
        jScrollPane1.setViewportView(txtaNoiDung_Server);

        txtGui_Server.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        btnGui.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGui.setText("Gửi");
        btnGui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuiMouseClicked(evt);
            }
        });

        btnNhan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNhan.setText("Nhận");
        btnNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtGui_Server)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnGui)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnNhan))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCong)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnKhoiDong)))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhoiDong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGui_Server, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGui)
                    .addComponent(btnNhan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhoiDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhoiDongMouseClicked
        khoiDong();
    }//GEN-LAST:event_btnKhoiDongMouseClicked

    private void btnGuiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuiMouseClicked
        gui();
    }//GEN-LAST:event_btnGuiMouseClicked

    private void btnNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanMouseClicked
        nhan();
    }//GEN-LAST:event_btnNhanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai2_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai2_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai2_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai2_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai2_Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGui;
    private javax.swing.JButton btnKhoiDong;
    private javax.swing.JButton btnNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCong;
    private javax.swing.JTextField txtGui_Server;
    private javax.swing.JTextArea txtaNoiDung_Server;
    // End of variables declaration//GEN-END:variables
}
